using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using Bom.ReportingService.DTOs;

namespace Bom.ReportingService.Reports.Pdf
{
    public class BomPdfGenerator
    {
        public byte[] Generate(BomDto bom)
        {
            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(30);

                   
                    page.Header().Background(Colors.Grey.Lighten2).Padding(10).AlignCenter().Text(text =>
                    {
                        text.Span($"BILL OF MATERIAL REPORT (Version: {bom.Version ?? "N/A"})")
                            .FontSize(20)
                            .Bold();
                    });

                    page.Content().PaddingTop(20).Column(col =>
                    {
                        
                        col.Item().Text($"BOM ID: {bom.Id}");
                        col.Item().Text($"Created At: {bom.CreatedAt}");
                        col.Item().PaddingVertical(10);

                       
                        col.Item().Table(table =>
                        {
                            table.ColumnsDefinition(columns =>
                            {
                                columns.RelativeColumn(4);
                                columns.RelativeColumn(1);
                            });

                          
                            table.Header(header =>
                            {
                                header.Cell().Element(CellStyle).Text("Part Name").Bold();
                                header.Cell().Element(CellStyle).Text("Quantity").Bold();
                            });

                            
                            foreach (var item in bom.Items)
                            {
                                AddRows(table, item, 0);
                            }
                        });
                    });

                  
                    page.Footer().AlignCenter().Text("Generated by BOM Reporting Service");
                });
            });

            return document.GeneratePdf();
        }

      
        private void AddRows(TableDescriptor table, BomItemDto item, int level)
        {
            table.Cell().Element(CellStyle)
                .Text(new string(' ', level * 4) + item.Name);

            table.Cell().Element(CellStyle)
                .Text(item.Quantity.ToString());

            if (item.Children != null && item.Children.Any())
            {
                foreach (var child in item.Children)
                {
                    AddRows(table, child, level + 1);
                }
            }
        }

      
        private static IContainer CellStyle(IContainer container)
        {
            return container
                .Border(1)
                .BorderColor(Colors.Grey.Lighten2)
                .Padding(8);
        }
    }
}
